# Aula 09 — Operações vetorizadas e matrizes

**Módulo 3 — NumPy e Computação Numérica**

## Objetivos da aula

- Realizar cálculos diretamente sobre arrays, sem laços explícitos (vetorização).
- Entender o conceito de *broadcasting*.
- Trabalhar com matrizes (arrays 2D): criação, indexação e seleção de linhas e colunas.

---

## 1. Operações vetorizadas

Na Aula 04, para converter uma lista inteira de Celsius para Fahrenheit, precisamos de um `for` (ou uma *list comprehension*). Com arrays NumPy, a mesma operação é escrita **diretamente sobre o array inteiro**, sem laço explícito — isso é chamado de **vetorização**.

In [12]:
import numpy as np

leituras_celsius = np.array([72.0, 76.5, 91.0, 68.3, 85.2])

# a operação é aplicada a CADA elemento do array, automaticamente
leituras_fahrenheit = leituras_celsius * 9 / 5 + 32

print("Celsius:   ", leituras_celsius)
print("Fahrenheit:", np.round(leituras_fahrenheit, 1))


Celsius:    [72.  76.5 91.  68.3 85.2]
Fahrenheit: [161.6 169.7 195.8 154.9 185.4]


Além de ser muito mais concisa, a vetorização é **muito mais rápida** que o laço `for` equivalente, especialmente com milhares ou milhões de valores — o NumPy executa o cálculo em código compilado, evitando o custo de repetir a operação em Python puro a cada iteração.

## 2. Operações entre dois arrays

Quando os arrays têm o mesmo tamanho, as operações são feitas **elemento a elemento**.

In [13]:
temperatura_motor = np.array([72.0, 76.5, 91.0, 68.3])
temperatura_ambiente = np.array([25.0, 26.0, 24.5, 25.5])

diferenca = temperatura_motor - temperatura_ambiente
print("Diferença motor - ambiente:", diferenca)

media_dos_dois = (temperatura_motor + temperatura_ambiente) / 2
print("Média:", media_dos_dois)


Diferença motor - ambiente: [47.  50.5 66.5 42.8]
Média: [48.5  51.25 57.75 46.9 ]


## 3. *Broadcasting*

O NumPy também permite operar um array com um único número (*escalar*), aplicando a operação a todos os elementos — isso é chamado de ***broadcasting***. Já fizemos isso sem perceber: `leituras_celsius * 9 / 5 + 32` fez *broadcasting* do `9`, `5` e `32` para todos os elementos do array.

In [14]:
leituras = np.array([72.0, 76.5, 91.0, 68.3])
ajuste_calibracao = 1.5   # escalar: um único número

leituras_calibradas = leituras + ajuste_calibracao   # somado a TODOS os elementos
print("Leituras calibradas:", leituras_calibradas)


Leituras calibradas: [73.5 78.  92.5 69.8]


## 4. Matrizes: arrays de duas dimensões

Uma **matriz** é um array 2D: linhas e colunas. É útil para organizar, por exemplo, várias leituras (colunas) de vários sensores (linhas).

In [15]:
# cada linha representa um equipamento; cada coluna, uma leitura ao longo do tempo
leituras_por_equipamento = np.array([
    [72.0, 74.5, 76.0, 75.2],   # Motor-01
    [65.2, 66.8, 64.1, 65.9],   # Bomba-03
    [88.0, 90.5, 91.2, 89.7],   # Compressor-02
])

print(leituras_por_equipamento)
print("Formato (linhas, colunas):", leituras_por_equipamento.shape)


[[72.  74.5 76.  75.2]
 [65.2 66.8 64.1 65.9]
 [88.  90.5 91.2 89.7]]
Formato (linhas, colunas): (3, 4)


## 5. Indexação em matrizes

Usamos `matriz[linha, coluna]`. Também podemos selecionar linhas ou colunas inteiras usando `:`.

In [16]:
leituras_por_equipamento = np.array([
    [72.0, 74.5, 76.0, 75.2],   # Motor-01     (linha 0)
    [65.2, 66.8, 64.1, 65.9],   # Bomba-03     (linha 1)
    [88.0, 90.5, 91.2, 89.7],   # Compressor-02 (linha 2)
])

print("Elemento na linha 0, coluna 2:", leituras_por_equipamento[0, 2])
print("Todas as leituras do Compressor-02 (linha 2):", leituras_por_equipamento[2, :])
print("Todas as leituras no instante 0 (coluna 0):", leituras_por_equipamento[:, 0])
print("Duas primeiras linhas, duas últimas colunas:")
print(leituras_por_equipamento[0:2, 2:4])


Elemento na linha 0, coluna 2: 76.0
Todas as leituras do Compressor-02 (linha 2): [88.  90.5 91.2 89.7]
Todas as leituras no instante 0 (coluna 0): [72.  65.2 88. ]
Duas primeiras linhas, duas últimas colunas:
[[76.  75.2]
 [64.1 65.9]]


## 6. Operações ao longo de linhas e colunas (`axis`)

Muitas funções do NumPy aceitam o parâmetro `axis` para indicar a **direção** do cálculo:

- `axis=0` → percorre as **linhas**, ou seja, calcula "por coluna" (por instante de tempo).
- `axis=1` → percorre as **colunas**, ou seja, calcula "por linha" (por equipamento).

In [17]:
leituras_por_equipamento = np.array([
    [72.0, 74.5, 76.0, 75.2],   # Motor-01
    [65.2, 66.8, 64.1, 65.9],   # Bomba-03
    [88.0, 90.5, 91.2, 89.7],   # Compressor-02
])

media_por_equipamento = leituras_por_equipamento.mean(axis=1)   # uma média por linha
media_por_instante = leituras_por_equipamento.mean(axis=0)      # uma média por coluna

print("Média de temperatura por equipamento:", np.round(media_por_equipamento, 1))
print("Média de temperatura por instante:   ", np.round(media_por_instante, 1))


Média de temperatura por equipamento: [74.4 65.5 89.8]
Média de temperatura por instante:    [75.1 77.3 77.1 76.9]


## 7. Transposição e reshape

`transpose()` (ou `.T`) troca linhas por colunas. `reshape()` reorganiza os elementos em um novo formato, mantendo a mesma quantidade total.

In [18]:
leituras_por_equipamento = np.array([
    [72.0, 74.5, 76.0, 75.2],
    [65.2, 66.8, 64.1, 65.9],
    [88.0, 90.5, 91.2, 89.7],
])

print("Transposta (instantes nas linhas, equipamentos nas colunas):")
print(leituras_por_equipamento.T)

sequencia = np.arange(12)
print("\nSequência original:", sequencia)
print("Reorganizada em 3 linhas x 4 colunas:")
print(sequencia.reshape(3, 4))


Transposta (instantes nas linhas, equipamentos nas colunas):
[[72.  65.2 88. ]
 [74.5 66.8 90.5]
 [76.  64.1 91.2]
 [75.2 65.9 89.7]]

Sequência original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reorganizada em 3 linhas x 4 colunas:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 8. Resumo da aula

- Operações vetorizadas aplicam um cálculo a todo o array de uma vez, sem laços explícitos — mais rápido e mais legível.
- *Broadcasting* permite operar um array com um escalar (ou arrays de formatos compatíveis).
- Matrizes são arrays 2D; acessamos elementos com `matriz[linha, coluna]`.
- `axis=0` opera por coluna, `axis=1` opera por linha.
- `.T` transpõe uma matriz; `.reshape()` reorganiza os elementos em outro formato.

### Exercício sugerido

Crie uma matriz `3x3` com leituras de vibração de 3 equipamentos em 3 instantes. Calcule a média de vibração por equipamento (`axis=1`) e identifique, usando indexação booleana, quais médias ultrapassam `3.0`.
